-- Dados iniciais exclusivos da Autêntica Professional.
begin;

insert into public.tenants (id, slug, name, status, plan)
values ('00000000-0000-4000-8000-000000000100', 'autentica', 'Autêntica Professional', 'active', 'pro')
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  status = excluded.status,
  plan = excluded.plan;

insert into public.store_settings (
  tenant_id, id, store_name, logo_url, favicon_url, whatsapp, order_prefix, email,
  hours, announcement, footer_description, primary_color, secondary_color,
  background_color, text_color, font_family, header_layout, content_width,
  border_radius, free_shipping_threshold, shipping_flat, free_shipping_enabled,
  free_shipping_banner_enabled, free_shipping_banner_eyebrow,
  free_shipping_banner_title, free_shipping_banner_subtitle,
  free_shipping_banner_button_text, free_shipping_banner_button_link,
  pix_discount, auto_banner_seconds, checkout_mode, show_prices, whatsapp_message
)
values (
  '00000000-0000-4000-8000-000000000100', 'default', 'Autêntica Professional',
  '/assets/logo-autentica-original.webp', '/client-brand.svg', '5531985674049', 'AUT',
  'contato@autenticaprofessional.com.br', 'Segunda a sexta · 8h às 18h',
  'Catálogo profissional para salão, revenda e cliente final',
  'Beleza profissional com produtos para transformação, tratamento e finalização. Solicite condições diretamente com a nossa equipe.',
  '#D51F32', '#A90F20', '#07090D', '#F5F7FB', 'Manrope', 'left', 1240, 18,
  0, 0, false, false, 'ATENDIMENTO ESPECIALIZADO',
  'Condições personalizadas para cada perfil.',
  'Fale com a equipe Autêntica e receba uma proposta adequada ao seu negócio.',
  'Solicitar orçamento', '#catalogo', 0, 7, 'whatsapp', false,
  $message$✨ *Nova solicitação de orçamento — {{loja}}*

📦 *Solicitação:* {{pedido}}

*Produtos de interesse:*
{{itens}}

👤 *Dados para atendimento:*
{{cliente}}

Por favor, envie disponibilidade, valores e condições comerciais.$message$
)
on conflict (tenant_id, id) do update set
  store_name = excluded.store_name, logo_url = excluded.logo_url,
  favicon_url = excluded.favicon_url, whatsapp = excluded.whatsapp,
  order_prefix = excluded.order_prefix, email = excluded.email,
  hours = excluded.hours, announcement = excluded.announcement,
  footer_description = excluded.footer_description,
  primary_color = excluded.primary_color, secondary_color = excluded.secondary_color,
  background_color = excluded.background_color, text_color = excluded.text_color,
  font_family = excluded.font_family, header_layout = excluded.header_layout,
  content_width = excluded.content_width, border_radius = excluded.border_radius,
  free_shipping_threshold = excluded.free_shipping_threshold,
  shipping_flat = excluded.shipping_flat,
  free_shipping_enabled = excluded.free_shipping_enabled,
  free_shipping_banner_enabled = excluded.free_shipping_banner_enabled,
  free_shipping_banner_eyebrow = excluded.free_shipping_banner_eyebrow,
  free_shipping_banner_title = excluded.free_shipping_banner_title,
  free_shipping_banner_subtitle = excluded.free_shipping_banner_subtitle,
  free_shipping_banner_button_text = excluded.free_shipping_banner_button_text,
  free_shipping_banner_button_link = excluded.free_shipping_banner_button_link,
  pix_discount = excluded.pix_discount, auto_banner_seconds = excluded.auto_banner_seconds,
  checkout_mode = excluded.checkout_mode, show_prices = excluded.show_prices,
  whatsapp_message = excluded.whatsapp_message;

-- AUTENTICA_CATALOG_START
delete from public.products where tenant_id = '00000000-0000-4000-8000-000000000100';
delete from public.categories where tenant_id = '00000000-0000-4000-8000-000000000100';

insert into public.categories (tenant_id, id, name, slug, active, order_index) values
  ('00000000-0000-4000-8000-000000000100', 'cat-01', 'Transformação', 'transformacao', true, 1),
  ('00000000-0000-4000-8000-000000000100', 'cat-02', 'Reconstrução', 'reconstrucao', true, 2),
  ('00000000-0000-4000-8000-000000000100', 'cat-03', 'Hidratação', 'hidratacao', true, 3),
  ('00000000-0000-4000-8000-000000000100', 'cat-04', 'Nutrição', 'nutricao', true, 4),
  ('00000000-0000-4000-8000-000000000100', 'cat-05', 'Limpeza e reposição de carbono', 'limpeza-e-reposicao-de-carbono', true, 5),
  ('00000000-0000-4000-8000-000000000100', 'cat-06', 'Limpeza profissional', 'limpeza-profissional', true, 6),
  ('00000000-0000-4000-8000-000000000100', 'cat-07', 'Condicionamento', 'condicionamento', true, 7),
  ('00000000-0000-4000-8000-000000000100', 'cat-08', 'Condicionamento profissional', 'condicionamento-profissional', true, 8),
  ('00000000-0000-4000-8000-000000000100', 'cat-09', 'Tratamento', 'tratamento', true, 9),
  ('00000000-0000-4000-8000-000000000100', 'cat-10', 'Tratamento profissional', 'tratamento-profissional', true, 10),
  ('00000000-0000-4000-8000-000000000100', 'cat-11', 'Finalização do tratamento', 'finalizacao-do-tratamento', true, 11),
  ('00000000-0000-4000-8000-000000000100', 'cat-12', 'Hidro nutritivo', 'hidro-nutritivo', true, 12),
  ('00000000-0000-4000-8000-000000000100', 'cat-13', 'Reparação premium', 'reparacao-premium', true, 13),
  ('00000000-0000-4000-8000-000000000100', 'cat-14', 'Cauterização', 'cauterizacao', true, 14),
  ('00000000-0000-4000-8000-000000000100', 'cat-15', 'Cronograma rápido', 'cronograma-rapido', true, 15),
  ('00000000-0000-4000-8000-000000000100', 'cat-16', 'Loiros', 'loiros', true, 16),
  ('00000000-0000-4000-8000-000000000100', 'cat-17', 'Terapia capilar', 'terapia-capilar', true, 17),
  ('00000000-0000-4000-8000-000000000100', 'cat-18', 'Cachos', 'cachos', true, 18),
  ('00000000-0000-4000-8000-000000000100', 'cat-19', 'Finalização', 'finalizacao', true, 19),
  ('00000000-0000-4000-8000-000000000100', 'cat-20', 'Lavatório', 'lavatorio', true, 20);

insert into public.products (
  tenant_id, id, slug, name, category_id, brand, price, compare_at, cashback,
  cost_price, stock, min_stock, badge, accent, description, tagline, need,
  audiences, indication, result, sku, rating, reviews, featured, active,
  order_index, image_url, image_urls, product_type, regulatory_status,
  active_ingredient, anvisa_registration, presentation, regulatory_warning,
  pharmacist_reviewed
) values
  ('00000000-0000-4000-8000-000000000100', 'aut-001', 'terra-acai', 'Terra Açaí', 'cat-01', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, 'Destaque', '#D51F32', 'Indicada para profissionais que precisam entregar redução de volume com apelo orgânico e resultado visual de alto impacto.', 'Escova orgânica para liso total com saúde e força.', 'Redução de volume', array['b2b']::text[], 'Redução de volume, alinhamento e controle de frizz em serviços de salão.', 'Alisamento total, fios mais fortes e acabamento saudável.', 'AUT-001', 5, 0, true, true, 1, '/assets/drive-products/terra-acai.webp', '["/assets/drive-products/terra-acai.webp"]'::jsonb, 'non_medicine', 'approved', 'Blend orgânico.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-002', 'ta-liso', 'Tá Liso', 'cat-01', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Linha de escova para redução de volume em serviços profissionais, pensada para selar e fixar o formato desejado.', 'Escova sinérgica com ativação térmica.', 'Redução de volume', array['b2b']::text[], 'Alinhamento de cutículas e modelagem da nova forma dos fios.', 'Fios alinhados, disciplinados e com liso potencializado.', 'AUT-002', 5, 0, false, true, 2, '/assets/drive-products/ta-liso.webp', '["/assets/drive-products/ta-liso.webp"]'::jsonb, 'non_medicine', 'approved', 'Tecnologia termoativada pela prancha.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-003', 'reforce-xtreme-btx', 'Reforce Xtreme BTX', 'cat-01', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'BTX profissional para entregar efeito de selagem e acabamento polido enquanto ajuda a repor massa na fibra.', 'Máscara termoativada para reposição de massa.', 'Redução de volume', array['b2b']::text[], 'Todos os tipos de cabelo que precisam de selagem e disciplina.', 'Fios lisos, selados e iluminados.', 'AUT-003', 5, 0, false, true, 3, '/assets/products/reforce-xtreme-btx.webp', '["/assets/products/reforce-xtreme-btx.webp"]'::jsonb, 'non_medicine', 'approved', 'Repositor de massa com ação termoativada.', '', 'Reforce Xtreme — Reposição de massa', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-004', 'extrato-floresta-luxeplastica', 'Extrato Floresta Luxeplástica', 'cat-01', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Tratamento de transformação para profissionais que querem unir cauterização, definição e redução de volume em uma única oferta.', 'Luxeplástica com ativos da Amazônia.', 'Redução de volume', array['b2b']::text[], 'Cauterização com redução de frizz e alinhamento das cutículas.', 'Liso extreme, nutrição no córtex e brilho.', 'AUT-004', 5, 0, false, true, 4, '/assets/products/extrato-floresta-luxeplastica.webp', '["/assets/products/extrato-floresta-luxeplastica.webp"]'::jsonb, 'non_medicine', 'approved', 'Ativos da Floresta Amazônica e efeito orgânico.', '', 'Extrato Floresta — Luxeplástica', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-005', 'btx-blond', 'BTX Blond', 'cat-01', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Opção de redução de volume para fios com cor, pensada para evitar amarelamento e envelhecimento visual do cabelo.', 'Restaurador capilar com pigmento matizante.', 'Redução de volume', array['b2b']::text[], 'Cabelos cacheados, crespos ou indisciplinados com necessidade de reduzir volume.', 'Reduz volume e minimiza oxidação da cor.', 'AUT-005', 5, 0, false, true, 5, '/assets/products/btx-blond.webp', '["/assets/products/btx-blond.webp"]'::jsonb, 'non_medicine', 'approved', 'Pigmentos matizantes para proteção da cor.', '', 'BTX Blond — Restaurador capilar', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-006', 'ouro-argan', 'Ouro Argan', 'cat-02', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, 'Destaque', '#D51F32', 'Linha de cronograma capilar voltada para reconstrução essencial e recuperação de fios fragilizados.', 'Reconstrução para fibra quebradiça.', 'Cronograma capilar', array['b2b', 'b2c', 'resale']::text[], 'Fios quebradiços, opacos e enfraquecidos.', 'Reparação profunda e recuperação da fibra capilar.', 'AUT-006', 5, 0, true, true, 6, '/assets/drive-products/ouro-argan.webp', '["/assets/drive-products/ouro-argan.webp"]'::jsonb, 'non_medicine', 'approved', 'Argan e Monoi.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-007', 'geleia-real', 'Geleia Real', 'cat-03', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Tratamento equilibrante para trazer maciez, resistência e resposta mais rápida aos demais ativos do cronograma.', 'Hidratação inteligente com alta carga proteica.', 'Cronograma capilar', array['b2b', 'b2c', 'resale']::text[], 'Fios danificados que precisam repor água e nutrientes.', 'Recupera, fortalece e protege a fibra.', 'AUT-007', 5, 0, false, true, 7, '/assets/drive-products/geleia-real.webp', '["/assets/drive-products/geleia-real.webp"]'::jsonb, 'non_medicine', 'approved', 'Extrato de mel e proteínas.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-008', 'super-nutri', 'Super Nutri', 'cat-04', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Linha de nutrição para recuperar toque, flexibilidade e brilho em cabelos que passaram por processos químicos.', 'Fusão de lipídeos para pós-química.', 'Cronograma capilar', array['b2b', 'b2c', 'resale']::text[], 'Pós-mechas, pós-progressiva e fios ressecados.', 'Regenera o manto hidrolipídico e sela áreas porosas.', 'AUT-008', 5, 0, false, true, 8, '/assets/drive-products/super-nutri.webp', '["/assets/drive-products/super-nutri.webp"]'::jsonb, 'non_medicine', 'approved', 'Lipídeos e sistema nutritivo.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-009', 'morango-champagne-shampoo-500ml', 'Shampoo Morango & Champagne 500 ml', 'cat-05', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Shampoo de 500 ml da linha Morango & Champagne, com proposta antioxidante, redução de danos e nutrição intensa.', 'Limpeza nutritiva para iniciar o protocolo de reposição de carbono.', 'Cronograma capilar', array['b2b', 'b2c', 'resale']::text[], 'Rotinas de cuidado para cabelos com aparência danificada e necessidade de nutrição.', 'Limpa os fios e prepara o cabelo para as próximas etapas da linha.', 'AUT-009', 5, 0, false, true, 9, '/assets/products/morango-champagne-shampoo-500ml.webp', '["/assets/products/morango-champagne-shampoo-500ml.webp"]'::jsonb, 'non_medicine', 'approved', 'Vitaminas A, B e C e frutas vermelhas.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-010', 'morango-champagne-shampoo-1l', 'Shampoo Morango & Champagne 1 L', 'cat-06', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Versão de 1 litro do shampoo Morango & Champagne, indicada para integrar protocolos profissionais de cuidado nutritivo.', 'Formato profissional para protocolos de reposição de carbono.', 'Cronograma capilar', array['b2b', 'resale']::text[], 'Salões e profissionais que precisam de maior rendimento no lavatório.', 'Limpeza preparatória com rendimento para a rotina profissional.', 'AUT-010', 5, 0, false, true, 10, '/assets/products/morango-champagne-shampoo-1l.webp', '["/assets/products/morango-champagne-shampoo-1l.webp"]'::jsonb, 'non_medicine', 'approved', 'Vitaminas A, B e C e frutas vermelhas.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-011', 'morango-champagne-condicionador-500ml', 'Condicionador Morango & Champagne 500 ml', 'cat-07', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Condicionador de 500 ml para complementar a rotina de reposição de carbono da linha Morango & Champagne.', 'Condicionamento nutritivo com ação antioxidante.', 'Cronograma capilar', array['b2b', 'b2c', 'resale']::text[], 'Cabelos com aparência danificada que precisam de cuidado e nutrição.', 'Complementa a rotina deixando os fios com aspecto mais cuidado.', 'AUT-011', 5, 0, false, true, 11, '/assets/products/morango-champagne-condicionador-500ml.webp', '["/assets/products/morango-champagne-condicionador-500ml.webp"]'::jsonb, 'non_medicine', 'approved', 'Vitaminas A, B e C e frutas vermelhas.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-012', 'morango-champagne-condicionador-1l', 'Condicionador Morango & Champagne 1 L', 'cat-08', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Versão profissional de 1 litro do condicionador Morango & Champagne, pensada para maior rendimento no salão.', 'Condicionamento profissional com nutrição intensa.', 'Cronograma capilar', array['b2b', 'resale']::text[], 'Uso profissional em protocolos de reposição de carbono e cuidado nutritivo.', 'Finaliza a etapa de lavagem e ajuda a manter os fios condicionados.', 'AUT-012', 5, 0, false, true, 12, '/assets/products/morango-champagne-condicionador-1l.webp', '["/assets/products/morango-champagne-condicionador-1l.webp"]'::jsonb, 'non_medicine', 'approved', 'Vitaminas A, B e C e frutas vermelhas. Faixa de pH indicada no rótulo: 4,5 a 5,5.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-013', 'morango-champagne-mascara-500g', 'Máscara Morango & Champagne 500 g', 'cat-09', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, 'Destaque', '#D51F32', 'Máscara de 500 g da linha Morango & Champagne para incluir a reposição de carbono no cronograma capilar.', 'Tratamento concentrado para reposição de carbono.', 'Cronograma capilar', array['b2b', 'b2c', 'resale']::text[], 'Cabelos com aparência danificada que precisam de uma etapa concentrada de nutrição.', 'Apoia o cuidado da fibra com ação antioxidante e nutrição intensa.', 'AUT-013', 5, 0, true, true, 13, '/assets/products/morango-champagne-mascara-500g.webp', '["/assets/products/morango-champagne-mascara-500g.webp"]'::jsonb, 'non_medicine', 'approved', 'Vitaminas A, B e C e frutas vermelhas. Faixa de pH indicada no rótulo: 3,0 a 4,0.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-014', 'morango-champagne-mascara-1kg', 'Máscara Morango & Champagne 1 kg', 'cat-10', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Máscara de 1 kg da linha Morango & Champagne, em tamanho profissional para protocolos de tratamento no salão.', 'Máscara profissional para protocolos de nutrição intensa.', 'Cronograma capilar', array['b2b', 'resale']::text[], 'Salões que realizam tratamentos de reposição de carbono e recuperação visual dos fios.', 'Entrega uma etapa concentrada de tratamento com rendimento profissional.', 'AUT-014', 5, 0, false, true, 14, '/assets/products/morango-champagne-mascara-1kg.webp', '["/assets/products/morango-champagne-mascara-1kg.webp"]'::jsonb, 'non_medicine', 'approved', 'Vitaminas A, B e C e frutas vermelhas. Faixa de pH indicada no rótulo: 3,0 a 4,0.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-015', 'morango-champagne-bb-cream-500ml', 'BB Cream Morango & Champagne 500 ml', 'cat-11', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'BB Cream de 500 ml da linha Morango & Champagne, apresentado como etapa complementar do protocolo de reposição de carbono.', 'BB Cream para completar a rotina de reposição de carbono.', 'Cronograma capilar', array['b2b', 'b2c', 'resale']::text[], 'Finalização da rotina Morango & Champagne em cabelos com aparência danificada.', 'Completa o protocolo com cuidado nutritivo e acabamento dos fios.', 'AUT-015', 5, 0, false, true, 15, '/assets/products/morango-champagne-bb-cream-500ml.webp', '["/assets/products/morango-champagne-bb-cream-500ml.webp"]'::jsonb, 'non_medicine', 'approved', 'Vitaminas A, B e C e frutas vermelhas. Faixa de pH indicada no rótulo: 3,0 a 4,0.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-016', 'sos', 'S.O.S', 'cat-12', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Tratamento para recuperar o aspecto de fios fragilizados, com foco em resistencia e toque.', 'Linha anti-quebra e anti-pontas duplas.', 'Cronograma capilar', array['b2b', 'b2c', 'resale']::text[], 'Fios descuticulados, quebradiços e com dificuldade de desembaraço.', 'Reduz quebra, melhora desembaraço e encorpa a fibra.', 'AUT-016', 5, 0, false, true, 16, '/assets/drive-products/sos.webp', '["/assets/drive-products/sos.webp"]'::jsonb, 'non_medicine', 'approved', 'Sistema hidro nutritivo para aumento de espessura do fio.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-017', 'sos-premium-elixir-repair', 'S.O.S Premium Elixir Repair', 'cat-13', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, 'Destaque', '#D51F32', 'Linha premium de reparação capilar criada para transformar o diagnóstico de fios fragilizados em uma rotina de tratamento e manutenção.', 'Tecnologia avançada em reparação capilar.', 'Cronograma capilar', array['b2b', 'b2c', 'resale']::text[], 'Fios fragilizados, com quebra, pontas duplas, opacidade e sinais de dano.', 'Ajuda a melhorar resistência cosmética, selagem visual, maciez e brilho.', 'AUT-017', 5, 0, true, true, 17, '/assets/lancamentos/sos-premium-elixir-repair-foto-produtos.webp', '["/assets/lancamentos/sos-premium-elixir-repair-foto-produtos.webp"]'::jsonb, 'non_medicine', 'approved', 'Tecnologia de reparação premium com foco em anti-quebra, selagem visual de cutículas e cuidado das pontas.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-018', 'desfibrilador', 'Desfibrilador', 'cat-14', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Tratamento intenso para bancada profissional, criado para balancear pH e recuperar cabelos em estado critico.', 'S.O.S. para emborrachamento e dano severo.', 'Cronograma capilar', array['b2b']::text[], 'Pontas danificadas, emborrachamento e fibra desestabilizada.', 'Repõe massa, neutraliza química e reestrutura a fibra.', 'AUT-018', 5, 0, false, true, 18, '/assets/drive-products/desfibrilador.webp', '["/assets/drive-products/desfibrilador.webp"]'::jsonb, 'non_medicine', 'approved', 'Queratina vegetal, Luna Matrix e ação acidificante.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-019', 'ampolas-3-etapas', 'Ampolas 3 Etapas', 'cat-15', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Kit compacto para transformar diagnostico em rotina simples de tres etapas essenciais.', 'Reconstrução, nutrição e hidratação em rotina rápida.', 'Cronograma capilar', array['b2b', 'b2c', 'resale']::text[], 'Manutenção acelerada do cronograma capilar.', 'Fortalece, nutre e devolve água para fios saudáveis.', 'AUT-019', 5, 0, false, true, 19, '/assets/drive-products/ampolas-3-etapas.webp', '["/assets/drive-products/ampolas-3-etapas.webp"]'::jsonb, 'non_medicine', 'approved', 'Óleos, lipídeos e ativos nutritivos.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-020', 'po-descolorante', 'Pó Descolorante', 'cat-16', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Produto obrigatório para salões que trabalham com transformações em loiros e precisam equilibrar técnica e segurança.', 'Clareamento para mechas, luzes e decapagem.', 'Loiros e descoloração', array['b2b']::text[], 'Técnicas de mechas, luzes e decapagens.', 'Loiro luminoso com respeito à integridade dos fios.', 'AUT-020', 5, 0, false, true, 20, '/assets/products/po-descolorante.webp', '["/assets/products/po-descolorante.webp"]'::jsonb, 'non_medicine', 'approved', 'Sistema de descoloração profissional.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-021', 'black-platinum', 'Black Platinum', 'cat-16', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Linha de manutencao para neutralizar tons indesejados e entregar um visual platinado em loiros e grisalhos.', 'Linha matizadora para efeito platinado.', 'Loiros e descoloração', array['b2b', 'b2c', 'resale']::text[], 'Cabelos loiros, descoloridos ou grisalhos.', 'Efeito platinado e cor mais fria.', 'AUT-021', 5, 0, false, true, 21, '/produtos/black-platinum/assets/aplicacao.webp', '["/produtos/black-platinum/assets/aplicacao.webp"]'::jsonb, 'non_medicine', 'approved', 'Pigmentos especiais de alta tecnologia.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-022', 'silver-blond', 'Silver Blond', 'cat-16', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Tratamento de manutenção para tons loiros, com foco em brilho, proteção e efeito frio controlado.', 'Revitalização de loiros e neutralização do amarelado.', 'Loiros e descoloração', array['b2b', 'b2c', 'resale']::text[], 'Loiros com tonalidade amarelada.', 'Elimina o amarelado e protege a cor.', 'AUT-022', 5, 0, false, true, 22, '/assets/products/silver-blond.webp', '["/assets/products/silver-blond.webp"]'::jsonb, 'non_medicine', 'approved', 'Protein Collor, extrato violeta e complexo protetor.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-023', 'vita-hair', 'Vita Hair Vitamin Complex', 'cat-17', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Linha voltada para terapia capilar e retenção de clientes que buscam fortalecer fios fragilizados.', 'Blend vitamínico para fios enfraquecidos.', 'Terapia capilar', array['b2b', 'b2c', 'resale']::text[], 'Fios fracos após dengue, zika, chikungunya, covid-19 ou queda intensa.', 'Estimula crescimento e devolve força e brilho.', 'AUT-023', 5, 0, false, true, 23, '/assets/drive-products/vita-hair.webp', '["/assets/drive-products/vita-hair.webp"]'::jsonb, 'non_medicine', 'approved', 'Blend de vitaminas.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-024', 'therapy-detox', 'Therapy Detox', 'cat-17', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Produto de entrada para protocolos de limpeza profunda, preparando a fibra para melhor resposta aos tratamentos.', 'Shampoo purificante para couro cabeludo equilibrado.', 'Terapia capilar', array['b2b', 'b2c', 'resale']::text[], 'Acúmulo de resíduos, oleosidade e sensação de peso.', 'Remove impurezas, equilibra o couro cabeludo e traz frescor.', 'AUT-024', 5, 0, false, true, 24, '/assets/drive-products/therapy-detox.webp', '["/assets/drive-products/therapy-detox.webp"]'::jsonb, 'non_medicine', 'approved', 'Ingredientes detoxificantes e naturais.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-025', 'coffee', 'Coffee', 'cat-17', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Linha de tratamento para quem precisa de uma narrativa clara de crescimento, força e estimulação capilar.', 'Tratamento com cafeína para crescimento.', 'Terapia capilar', array['b2b', 'b2c', 'resale']::text[], 'Queda, crescimento lento e folículos enfraquecidos.', 'Estimula circulação no couro cabeludo e fortalece os fios.', 'AUT-025', 5, 0, false, true, 25, '/assets/drive-products/coffee.webp', '["/assets/drive-products/coffee.webp"]'::jsonb, 'non_medicine', 'approved', 'Cafeína.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-026', 'super-cachos', 'Super Cachos', 'cat-18', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, 'Destaque', '#D51F32', 'Linha para valorizar curvaturas com brilho, balanço e forma definida sem perder naturalidade.', 'Definição, memória do cacho e controle de frizz.', 'Finalizadores', array['b2b', 'b2c', 'resale']::text[], 'Todas as curvaturas que precisam de definição e movimento natural.', 'Reativa memória dos cachos, reduz volume e elimina frizz.', 'AUT-026', 5, 0, true, true, 26, '/assets/products/super-cachos-externo.webp', '["/assets/products/super-cachos-externo.webp"]'::jsonb, 'non_medicine', 'approved', 'Sistema de tratamento para cabelos ondulados, cacheados e crespos.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-027', 'inspira-parfum', 'Inspira Parfum', 'cat-19', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, 'Destaque', '#D51F32', 'Finalizador premium para gerar desejo imediato no lavatório e facilitar a revenda para manutenção em casa.', 'Perfume capilar com brilho intenso e efeito antifrizz.', 'Finalizadores', array['b2c', 'resale']::text[], 'Renovação do perfume e do acabamento dos fios ao longo do dia.', 'Perfuma, realça o brilho e ajuda no controle do frizz.', 'AUT-027', 5, 0, true, true, 27, '/assets/products/inspira-parfum-nova-embalagem.webp', '["/assets/products/inspira-parfum-nova-embalagem.webp"]'::jsonb, 'non_medicine', 'approved', 'Fragrância capilar com proteção solar declarada no rótulo.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-028', 'use-me-parfum', 'Use-Me Parfum', 'cat-19', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Produto de ticket rápido para a cliente levar a experiência do salão para a rotina.', 'Fragrância marcante com proteção solar.', 'Finalizadores', array['b2c', 'resale']::text[], 'Fios alinhados e saudáveis que pedem perfume e brilho.', 'Perfume intenso, proteção e controle de frizz.', 'AUT-028', 5, 0, false, true, 28, '/assets/products/use-me-parfum.webp', '["/assets/products/use-me-parfum.webp"]'::jsonb, 'non_medicine', 'approved', 'Fragrância capilar, proteção solar e anti-frizz.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-029', 'parfum-ouro-argan', 'Parfum Ouro Argan', 'cat-19', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Finalizador com proposta de luxo e tratamento, ideal para complementar serviços de reconstrução.', 'Perfume reconstrutor com textura leve.', 'Finalizadores', array['b2c', 'resale']::text[], 'Fios que precisam de perfume, resistência e vitalidade sem peso.', 'Reconstrução leve, maciez intensa e controle de frizz.', 'AUT-029', 5, 0, false, true, 29, '/assets/products/parfum-ouro-argan.webp', '["/assets/products/parfum-ouro-argan.webp"]'::jsonb, 'non_medicine', 'approved', 'Óleos vegetais.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-030', 'oleo-reparador-ouro-argan', 'Óleo Reparador Ouro Argan', 'cat-19', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Elixir de tratamento para vender no checkout e reforçar o resultado visual do serviço.', 'Óleo de tratamento com brilho radiante.', 'Finalizadores', array['b2c', 'resale']::text[], 'Fios com frizz, opacidade e pontas ressecadas.', 'Nutre profundamente, elimina frizz e restaura brilho.', 'AUT-030', 5, 0, false, true, 30, '/assets/drive-products/oleo-reparador-ouro-argan.webp', '["/assets/drive-products/oleo-reparador-ouro-argan.webp"]'::jsonb, 'non_medicine', 'approved', 'Óleo de Argan e Óleo de Monoi.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-031', 'luxe-oil-spa', 'Luxe Oil Spa', 'cat-19', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Óleo premium para finalizar serviços de tratamento e manter sensação de cabelo tratado por mais tempo.', 'Reconstrução total com toque de brilho.', 'Finalizadores', array['b2c', 'resale']::text[], 'Cabelos que precisam de reparação profunda e acabamento impecável.', 'Protege dos danos solares e recupera brilho.', 'AUT-031', 5, 0, false, true, 31, '/assets/products/luxe-oil-spa.webp', '["/assets/products/luxe-oil-spa.webp"]'::jsonb, 'non_medicine', 'approved', 'Sistema reparador com proteção solar.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-032', 'acai-oil', 'Açaí Oil', 'cat-19', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Óleo nutritivo para rotina de finalização, indicado para brilho rápido e proteção antes de fonte de calor.', 'Alto poder nutritivo com proteção térmica.', 'Finalizadores', array['b2c', 'resale']::text[], 'Fios que precisam selar cutícula e combater radicais livres.', 'Sela, nutre, protege do calor e restaura a fibra.', 'AUT-032', 5, 0, false, true, 32, '/assets/products/acai-oil.webp', '["/assets/products/acai-oil.webp"]'::jsonb, 'non_medicine', 'approved', 'Omegas 3 e 9 e vitaminas.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-033', 'ta-liso-zero-frizz', 'Tá Liso Finalizador 40 ml', 'cat-19', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Finalizador de 40 ml da linha Tá Liso para apoiar uma rotina de hidratação, proteção e selamento dos fios.', 'Hidratação, controle de frizz e selamento dos fios.', 'Finalizadores', array['b2c', 'resale']::text[], 'Finalização de cabelos que precisam de alinhamento, proteção e controle do frizz.', 'Fios mais alinhados, protegidos e luminosos.', 'AUT-033', 5, 0, false, true, 33, '/assets/products/ta-liso-finalizador-40ml.webp', '["/assets/products/ta-liso-finalizador-40ml.webp"]'::jsonb, 'non_medicine', 'approved', 'Sementes de feno-grego e óleo de girassol orgânico, com proteção térmica e solar declaradas no rótulo.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false),
  ('00000000-0000-4000-8000-000000000100', 'aut-034', 'perfect-argan-macadamia', 'Perfect Argan e Macadâmia', 'cat-20', 'Autêntica Professional', 0, 0, 0, 0, 999, 0, '', '#D51F32', 'Linha operacional para salões que precisam de rendimento, padronização de atendimento e boa experiência no lavatório.', 'Shampoo e condicionador profissional em galão 5L.', 'Uso profissional no lavatório', array['b2b']::text[], 'Operação de alto giro em lavatórios profissionais.', 'Hidratação com custo-benefício para rotina do salão.', 'AUT-034', 5, 0, false, true, 34, '/assets/drive-products/perfect-argan-macadamia.webp', '["/assets/drive-products/perfect-argan-macadamia.webp"]'::jsonb, 'non_medicine', 'approved', 'Argan e macadâmia.', '', 'Consulte as apresentações disponíveis', 'Uso profissional conforme indicação do fabricante.', false);
-- AUTENTICA_CATALOG_END

delete from public.coupons where tenant_id = '00000000-0000-4000-8000-000000000100';
delete from public.banners where tenant_id = '00000000-0000-4000-8000-000000000100';
delete from public.home_sections where tenant_id = '00000000-0000-4000-8000-000000000100';
delete from public.trust_items where tenant_id = '00000000-0000-4000-8000-000000000100';
delete from public.benefits where tenant_id = '00000000-0000-4000-8000-000000000100';
delete from public.faqs where tenant_id = '00000000-0000-4000-8000-000000000100';
delete from public.store_pages where tenant_id = '00000000-0000-4000-8000-000000000100';

insert into public.banners (
  tenant_id, id, kicker, title, highlight, subtitle, button_text, button_link,
  start_color, end_color, image_url, mobile_image_url, alt_text, image_only, active, order_index
) values
  ('00000000-0000-4000-8000-000000000100', 'banner-1', 'AUTÊNTICA PROFESSIONAL', 'Beleza profissional com identidade e resultado.', 'identidade e resultado.', 'Soluções para transformação, tratamento e finalização — do salão ao cuidado em casa.', 'Explorar catálogo', '#catalogo', '#171513', '#A90F20', '/assets/institucional/sos-premium-linha-bancada.webp', '/assets/institucional/sos-premium-linha-bancada.webp', 'Linha profissional Autêntica', false, true, 1),
  ('00000000-0000-4000-8000-000000000100', 'banner-2', 'DESTAQUE AUTÊNTICA', 'S.O.S Premium Elixir Repair.', 'Elixir Repair.', 'Reparação premium com foco em anti-quebra, cuidado das pontas e acabamento profissional.', 'Conhecer produto', '/produtos/sos-premium-elixir-repair', '#4B0C15', '#D51F32', '/assets/lancamentos/sos-premium-elixir-repair-foto-produtos.webp', '/assets/lancamentos/sos-premium-elixir-repair-foto-produtos.webp', 'S.O.S Premium Elixir Repair', false, true, 2);

insert into public.home_sections (
  tenant_id, id, kind, name, eyebrow, title, subtitle, button_text, button_link, active, order_index
) values
  ('00000000-0000-4000-8000-000000000100', 'section-featured', 'featured', 'Produtos em destaque', 'SELEÇÃO AUTÊNTICA', 'Linhas que entregam resultado.', 'Destaques para profissionais, revendedores e consumidores.', '', '', true, 1),
  ('00000000-0000-4000-8000-000000000100', 'section-catalog', 'catalog', 'Catálogo completo', 'CATÁLOGO PROFISSIONAL', 'Encontre a solução certa para cada necessidade.', 'Filtre por categoria, objetivo e perfil de atendimento.', '', '', true, 2),
  ('00000000-0000-4000-8000-000000000100', 'section-promo', 'promo', 'Atendimento comercial', 'FALE COM A AUTÊNTICA', 'Condições sob medida para o seu perfil.', 'Monte sua seleção e solicite um orçamento pelo WhatsApp.', 'Ver produtos', '#catalogo', false, 3),
  ('00000000-0000-4000-8000-000000000100', 'section-benefits', 'benefits', 'Por que Autêntica', 'PARCERIA PROFISSIONAL', 'Produtos e atendimento para fazer seu negócio evoluir.', 'Uma jornada simples, consultiva e conectada à equipe comercial.', '', '', true, 4),
  ('00000000-0000-4000-8000-000000000100', 'section-faq', 'faq', 'Dúvidas frequentes', 'PRECISA DE AJUDA?', 'Tudo o que você precisa antes de solicitar.', '', '', '', true, 5);

insert into public.trust_items (tenant_id, id, title, subtitle, order_index) values
  ('00000000-0000-4000-8000-000000000100', 'trust-1', 'Atendimento especializado', 'Orientação para escolher a linha ideal', 1),
  ('00000000-0000-4000-8000-000000000100', 'trust-2', 'Três perfis de compra', 'Salão, revenda e cliente final', 2),
  ('00000000-0000-4000-8000-000000000100', 'trust-3', 'Catálogo sempre atualizado', 'Produtos e conteúdos gerenciados no painel', 3),
  ('00000000-0000-4000-8000-000000000100', 'trust-4', 'Orçamento direto', 'Condições confirmadas pelo WhatsApp', 4);

insert into public.benefits (tenant_id, id, title, text, order_index) values
  ('00000000-0000-4000-8000-000000000100', 'benefit-1', 'Portfólio completo', 'Soluções para transformação, cronograma capilar, loiros, terapia e finalização.', 1),
  ('00000000-0000-4000-8000-000000000100', 'benefit-2', 'Escolha orientada', 'Filtros por necessidade e perfil ajudam você a encontrar os produtos adequados.', 2),
  ('00000000-0000-4000-8000-000000000100', 'benefit-3', 'Condições personalizadas', 'Valores, disponibilidade e condições são confirmados conforme o perfil do cliente.', 3),
  ('00000000-0000-4000-8000-000000000100', 'benefit-4', 'Contato sem intermediários', 'A solicitação chega estruturada diretamente à equipe Autêntica pelo WhatsApp.', 4);

insert into public.faqs (tenant_id, id, question, answer, order_index) values
  ('00000000-0000-4000-8000-000000000100', 'faq-1', 'O catálogo atende profissionais e consumidores?', 'Sim. Identifique seu perfil como salão/profissional, revenda ou cliente final para receber o atendimento adequado.', 1),
  ('00000000-0000-4000-8000-000000000100', 'faq-2', 'Por que os preços não aparecem?', 'As condições variam conforme perfil, quantidade e disponibilidade. Monte sua seleção e solicite um orçamento sem compromisso.', 2),
  ('00000000-0000-4000-8000-000000000100', 'faq-3', 'Como solicito um orçamento?', 'Adicione os produtos de interesse, preencha seus dados e envie a solicitação pelo WhatsApp. Nenhum pagamento é realizado no site.', 3),
  ('00000000-0000-4000-8000-000000000100', 'faq-4', 'Posso comprar para revender?', 'Sim. Selecione o perfil Revenda no formulário para que a equipe comercial apresente as condições correspondentes.', 4);

insert into public.store_pages (
  tenant_id, id, name, slug, title, description, active, show_in_navigation, is_home, order_index
) values
  ('00000000-0000-4000-8000-000000000100', 'home', 'Página inicial', 'inicio', 'Autêntica Professional', 'Catálogo profissional da Autêntica Professional.', true, false, true, 1),
  ('00000000-0000-4000-8000-000000000100', 'page-about', 'Sobre a Autêntica', 'sobre', 'Sobre a Autêntica Professional', 'Conheça a marca e nossa forma de atender.', true, true, false, 2);

insert into public.page_blocks (
  tenant_id, id, page_id, kind, name, eyebrow, title, body, button_text,
  button_link, image_url, background_color, text_color, container_width,
  padding_size, columns_count, active, order_index
) values
  ('00000000-0000-4000-8000-000000000100', 'block-home-hero', 'home', 'hero', 'Banners principais', '', '', '', '', '', '', '', '', 'full', 'none', 1, true, 1),
  ('00000000-0000-4000-8000-000000000100', 'block-home-trust', 'home', 'trust', 'Faixa de confiança', '', '', '', '', '', '', '', '', 'full', 'none', 4, true, 2),
  ('00000000-0000-4000-8000-000000000100', 'block-home-featured', 'home', 'featured', 'Produtos em destaque', '', '', '', '', '', '', '', '', 'normal', 'large', 4, true, 3),
  ('00000000-0000-4000-8000-000000000100', 'block-home-catalog', 'home', 'catalog', 'Catálogo completo', '', '', '', '', '', '', '', '', 'normal', 'large', 4, true, 4),
  ('00000000-0000-4000-8000-000000000100', 'block-home-promo', 'home', 'promo', 'Atendimento comercial', '', '', '', '', '', '', '', '', 'normal', 'large', 1, false, 5),
  ('00000000-0000-4000-8000-000000000100', 'block-home-benefits', 'home', 'benefits', 'Benefícios', '', '', '', '', '', '', '', '', 'normal', 'large', 4, true, 6),
  ('00000000-0000-4000-8000-000000000100', 'block-home-faq', 'home', 'faq', 'Dúvidas frequentes', '', '', '', '', '', '', '', '', 'normal', 'large', 1, true, 7),
  ('00000000-0000-4000-8000-000000000100', 'block-about-text', 'page-about', 'text', 'Apresentação', 'AUTÊNTICA PROFESSIONAL', 'Beleza profissional com propósito.', 'A Autêntica Professional desenvolve soluções para transformação, tratamento e finalização, conectando performance profissional, identidade e cuidado em cada etapa.', 'Ver catálogo', '/#catalogo', '/assets/logo-autentica-original.webp', '#F4EFE8', '#171513', 'narrow', 'large', 1, true, 1),
  ('00000000-0000-4000-8000-000000000100', 'block-about-cta', 'page-about', 'cta', 'Chamada para atendimento', 'FALE COM NOSSA EQUIPE', 'Encontre a linha ideal para você ou para o seu negócio.', 'Selecione os produtos do catálogo e envie sua solicitação. A equipe Autêntica retorna com disponibilidade, valores e condições.', 'Explorar catálogo', '/#catalogo', '', '#A90F20', '#FFFFFF', 'normal', 'medium', 1, true, 2);

commit;

-- Depois de criar o primeiro usuário no Supabase Auth, promova-o no SQL Editor:
-- update public.profiles
-- set role = 'owner', is_platform_admin = true,
--     permissions = array['dashboard','crm','customers','orders','finance','inventory','purchasing','reports','collaboration','copilot','catalog','store','marketing','settings','data','users']
-- where id = (select id from auth.users where email = 'SEU_EMAIL');
